version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    environment:
      DATABASE_URL: "postgresql://todo_user:todo_password@postgres:5432/todo_db"
      JWT_SECRET: "your-production-jwt-secret-change-this"
      JWT_EXPIRES_IN: "7d"
      PORT: 5000
      NODE_ENV: "production"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - todo-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:5000/api"
      NEXT_PUBLIC_APP_NAME: "Todo App"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge
